server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taxi_system?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
